CREATE TABLE [dbo].[FileHeader]
(
	[Id] INT IDENTITY NOT NULL,
	[IdCustomer] INT NOT NULL,
	[IdFileInfoConfig] INT NOT NULL,
	[IdDocument] VARCHAR(100) NULL,
	[AuthorizationDate] DATETIME NULL,
	[ExpantionDate] DATETIME NULL,
	[ExpirationDate] DATETIME NULL,
	[DocumentDate] DATETIME NULL,
	[ArrivalDate] DATETIME NULL,
	[ExchangeRate] DECIMAL(18,6) NULL,
	[Insurance] DECIMAL(18,6) NULL,
	[Cargo] DECIMAL(18,6) NULL,
	[IdCustom] INT NULL,
	[IdCountry]INT NULL,
	[IdWarranty]INT NULL,
	[IdCellar]INT NULL,
	[IdState] INT NULL,
	[IdCurrency] INT NULL,
	[IdResolution] INT NULL,
	[IdAccount] INT NULL,
	[Reviewed] BIT NOT NULL DEFAULT 0,
	[CIFTotal] DECIMAL(18,6) NULL,
	[LinesTotal] INT NULL,
	[RegisterDate] DATETIME NOT NULL,
	[RegisterUser] VARCHAR(60) NOT NULL,
	[CreateDate] DATETIME NOT NULL,
	[UpdateDate] DATETIME NULL,
	PRIMARY KEY([Id]),
	FOREIGN KEY([IdCustomer]) REFERENCES [Customer]([IdPerson]),
	FOREIGN KEY([IdFileInfoConfig]) REFERENCES [FileInfoConfig]([Id]),
	FOREIGN KEY([IdCustom]) REFERENCES [Customs]([Id]),
	FOREIGN KEY([IdCountry]) REFERENCES [Country]([Id]),
	FOREIGN KEY([IdWarranty]) REFERENCES [Warranty]([Id]),
	FOREIGN KEY([IdState]) REFERENCES [State]([Id]),
	FOREIGN KEY([IdCurrency]) REFERENCES [Currency]([Id]),
	FOREIGN KEY([IdResolution]) REFERENCES [Resolution]([Id]),
	FOREIGN KEY([IdAccount]) REFERENCES [Account]([Id]),
	FOREIGN KEY([IdCellar]) REFERENCES [Cellar]([Id])
)
go
create index idx_FileHeader_ca ON FileHeader (IdCustomer, IdAccount)
go