//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Index.Queue.OpaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsRespuestaDescargo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clsRespuestaDescargo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sIdEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        private long lOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaDescargoField;
        
        private double dCifQField;
        
        private double dDaiQField;
        
        private double dIvaQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sPolExpFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sPolImpFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sGeneraMultaField;
        
        private double dMontoMultaNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sRazonMultaNacField;
        
        private double dMontoMultaExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sRazonMultaExtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sIdEnvio {
            get {
                return this.sIdEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.sIdEnvioField, value) != true)) {
                    this.sIdEnvioField = value;
                    this.RaisePropertyChanged("sIdEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sCodRespuesta {
            get {
                return this.sCodRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.sCodRespuestaField, value) != true)) {
                    this.sCodRespuestaField = value;
                    this.RaisePropertyChanged("sCodRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long lOperacion {
            get {
                return this.lOperacionField;
            }
            set {
                if ((this.lOperacionField.Equals(value) != true)) {
                    this.lOperacionField = value;
                    this.RaisePropertyChanged("lOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sFechaDescargo {
            get {
                return this.sFechaDescargoField;
            }
            set {
                if ((object.ReferenceEquals(this.sFechaDescargoField, value) != true)) {
                    this.sFechaDescargoField = value;
                    this.RaisePropertyChanged("sFechaDescargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double dCifQ {
            get {
                return this.dCifQField;
            }
            set {
                if ((this.dCifQField.Equals(value) != true)) {
                    this.dCifQField = value;
                    this.RaisePropertyChanged("dCifQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double dDaiQ {
            get {
                return this.dDaiQField;
            }
            set {
                if ((this.dDaiQField.Equals(value) != true)) {
                    this.dDaiQField = value;
                    this.RaisePropertyChanged("dDaiQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double dIvaQ {
            get {
                return this.dIvaQField;
            }
            set {
                if ((this.dIvaQField.Equals(value) != true)) {
                    this.dIvaQField = value;
                    this.RaisePropertyChanged("dIvaQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sPolExpFecha {
            get {
                return this.sPolExpFechaField;
            }
            set {
                if ((object.ReferenceEquals(this.sPolExpFechaField, value) != true)) {
                    this.sPolExpFechaField = value;
                    this.RaisePropertyChanged("sPolExpFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sPolImpFecha {
            get {
                return this.sPolImpFechaField;
            }
            set {
                if ((object.ReferenceEquals(this.sPolImpFechaField, value) != true)) {
                    this.sPolImpFechaField = value;
                    this.RaisePropertyChanged("sPolImpFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string sGeneraMulta {
            get {
                return this.sGeneraMultaField;
            }
            set {
                if ((object.ReferenceEquals(this.sGeneraMultaField, value) != true)) {
                    this.sGeneraMultaField = value;
                    this.RaisePropertyChanged("sGeneraMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double dMontoMultaNac {
            get {
                return this.dMontoMultaNacField;
            }
            set {
                if ((this.dMontoMultaNacField.Equals(value) != true)) {
                    this.dMontoMultaNacField = value;
                    this.RaisePropertyChanged("dMontoMultaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string sRazonMultaNac {
            get {
                return this.sRazonMultaNacField;
            }
            set {
                if ((object.ReferenceEquals(this.sRazonMultaNacField, value) != true)) {
                    this.sRazonMultaNacField = value;
                    this.RaisePropertyChanged("sRazonMultaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double dMontoMultaExt {
            get {
                return this.dMontoMultaExtField;
            }
            set {
                if ((this.dMontoMultaExtField.Equals(value) != true)) {
                    this.dMontoMultaExtField = value;
                    this.RaisePropertyChanged("dMontoMultaExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string sRazonMultaExt {
            get {
                return this.sRazonMultaExtField;
            }
            set {
                if ((object.ReferenceEquals(this.sRazonMultaExtField, value) != true)) {
                    this.sRazonMultaExtField = value;
                    this.RaisePropertyChanged("sRazonMultaExt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpaService.WSOPASoap")]
    public interface WSOPASoap {
        
        // CODEGEN: Generating message contract since element name TestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        Index.Queue.OpaService.TestResponse Test(Index.Queue.OpaService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<Index.Queue.OpaService.TestResponse> TestAsync(Index.Queue.OpaService.TestRequest request);
        
        // CODEGEN: Generating message contract since element name psUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmValidarDescargo", ReplyAction="*")]
        Index.Queue.OpaService.wmValidarDescargoResponse wmValidarDescargo(Index.Queue.OpaService.wmValidarDescargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmValidarDescargo", ReplyAction="*")]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmValidarDescargoResponse> wmValidarDescargoAsync(Index.Queue.OpaService.wmValidarDescargoRequest request);
        
        // CODEGEN: Generating message contract since element name psUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmExistePoliza", ReplyAction="*")]
        Index.Queue.OpaService.wmExistePolizaResponse wmExistePoliza(Index.Queue.OpaService.wmExistePolizaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmExistePoliza", ReplyAction="*")]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmExistePolizaResponse> wmExistePolizaAsync(Index.Queue.OpaService.wmExistePolizaRequest request);
        
        // CODEGEN: Generating message contract since element name psUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmEnviarDescargo", ReplyAction="*")]
        Index.Queue.OpaService.wmEnviarDescargoResponse wmEnviarDescargo(Index.Queue.OpaService.wmEnviarDescargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmEnviarDescargo", ReplyAction="*")]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmEnviarDescargoResponse> wmEnviarDescargoAsync(Index.Queue.OpaService.wmEnviarDescargoRequest request);
        
        // CODEGEN: Generating message contract since element name psUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmEnviarDescargoFecha", ReplyAction="*")]
        Index.Queue.OpaService.wmEnviarDescargoFechaResponse wmEnviarDescargoFecha(Index.Queue.OpaService.wmEnviarDescargoFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmEnviarDescargoFecha", ReplyAction="*")]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmEnviarDescargoFechaResponse> wmEnviarDescargoFechaAsync(Index.Queue.OpaService.wmEnviarDescargoFechaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(Index.Queue.OpaService.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(Index.Queue.OpaService.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Index.Queue.OpaService.clsRespuestaDescargo TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(Index.Queue.OpaService.clsRespuestaDescargo TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmValidarDescargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmValidarDescargo", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmValidarDescargoRequestBody Body;
        
        public wmValidarDescargoRequest() {
        }
        
        public wmValidarDescargoRequest(Index.Queue.OpaService.wmValidarDescargoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmValidarDescargoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psClave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psExportadorNit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string psPolizaImportacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pLineaPolizaImport;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double pdUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string psPolizaExportacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int piLineaPolizaExport;
        
        public wmValidarDescargoRequestBody() {
        }
        
        public wmValidarDescargoRequestBody(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport) {
            this.psUsuario = psUsuario;
            this.psClave = psClave;
            this.psExportadorNit = psExportadorNit;
            this.psPolizaImportacion = psPolizaImportacion;
            this.pLineaPolizaImport = pLineaPolizaImport;
            this.pdUnidades = pdUnidades;
            this.psPolizaExportacion = psPolizaExportacion;
            this.piLineaPolizaExport = piLineaPolizaExport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmValidarDescargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmValidarDescargoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmValidarDescargoResponseBody Body;
        
        public wmValidarDescargoResponse() {
        }
        
        public wmValidarDescargoResponse(Index.Queue.OpaService.wmValidarDescargoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmValidarDescargoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Index.Queue.OpaService.clsRespuestaDescargo wmValidarDescargoResult;
        
        public wmValidarDescargoResponseBody() {
        }
        
        public wmValidarDescargoResponseBody(Index.Queue.OpaService.clsRespuestaDescargo wmValidarDescargoResult) {
            this.wmValidarDescargoResult = wmValidarDescargoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmExistePolizaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmExistePoliza", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmExistePolizaRequestBody Body;
        
        public wmExistePolizaRequest() {
        }
        
        public wmExistePolizaRequest(Index.Queue.OpaService.wmExistePolizaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmExistePolizaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psClave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string psTipoPoliza;
        
        public wmExistePolizaRequestBody() {
        }
        
        public wmExistePolizaRequestBody(string psUsuario, string psClave, string psPoliza, string psTipoPoliza) {
            this.psUsuario = psUsuario;
            this.psClave = psClave;
            this.psPoliza = psPoliza;
            this.psTipoPoliza = psTipoPoliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmExistePolizaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmExistePolizaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmExistePolizaResponseBody Body;
        
        public wmExistePolizaResponse() {
        }
        
        public wmExistePolizaResponse(Index.Queue.OpaService.wmExistePolizaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmExistePolizaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wmExistePolizaResult;
        
        public wmExistePolizaResponseBody() {
        }
        
        public wmExistePolizaResponseBody(bool wmExistePolizaResult) {
            this.wmExistePolizaResult = wmExistePolizaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmEnviarDescargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmEnviarDescargo", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmEnviarDescargoRequestBody Body;
        
        public wmEnviarDescargoRequest() {
        }
        
        public wmEnviarDescargoRequest(Index.Queue.OpaService.wmEnviarDescargoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmEnviarDescargoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psClave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psExportadorNit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string psPolizaImportacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pLineaPolizaImport;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double pdUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string psPolizaExportacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int piLineaPolizaExport;
        
        public wmEnviarDescargoRequestBody() {
        }
        
        public wmEnviarDescargoRequestBody(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport) {
            this.psUsuario = psUsuario;
            this.psClave = psClave;
            this.psExportadorNit = psExportadorNit;
            this.psPolizaImportacion = psPolizaImportacion;
            this.pLineaPolizaImport = pLineaPolizaImport;
            this.pdUnidades = pdUnidades;
            this.psPolizaExportacion = psPolizaExportacion;
            this.piLineaPolizaExport = piLineaPolizaExport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmEnviarDescargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmEnviarDescargoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmEnviarDescargoResponseBody Body;
        
        public wmEnviarDescargoResponse() {
        }
        
        public wmEnviarDescargoResponse(Index.Queue.OpaService.wmEnviarDescargoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmEnviarDescargoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Index.Queue.OpaService.clsRespuestaDescargo wmEnviarDescargoResult;
        
        public wmEnviarDescargoResponseBody() {
        }
        
        public wmEnviarDescargoResponseBody(Index.Queue.OpaService.clsRespuestaDescargo wmEnviarDescargoResult) {
            this.wmEnviarDescargoResult = wmEnviarDescargoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmEnviarDescargoFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmEnviarDescargoFecha", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmEnviarDescargoFechaRequestBody Body;
        
        public wmEnviarDescargoFechaRequest() {
        }
        
        public wmEnviarDescargoFechaRequest(Index.Queue.OpaService.wmEnviarDescargoFechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmEnviarDescargoFechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psClave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psExportadorNit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string psPolizaImportacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pLineaPolizaImport;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double pdUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string psPolizaExportacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int piLineaPolizaExport;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string psFechaCc;
        
        public wmEnviarDescargoFechaRequestBody() {
        }
        
        public wmEnviarDescargoFechaRequestBody(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport, string psFechaCc) {
            this.psUsuario = psUsuario;
            this.psClave = psClave;
            this.psExportadorNit = psExportadorNit;
            this.psPolizaImportacion = psPolizaImportacion;
            this.pLineaPolizaImport = pLineaPolizaImport;
            this.pdUnidades = pdUnidades;
            this.psPolizaExportacion = psPolizaExportacion;
            this.piLineaPolizaExport = piLineaPolizaExport;
            this.psFechaCc = psFechaCc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wmEnviarDescargoFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wmEnviarDescargoFechaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Index.Queue.OpaService.wmEnviarDescargoFechaResponseBody Body;
        
        public wmEnviarDescargoFechaResponse() {
        }
        
        public wmEnviarDescargoFechaResponse(Index.Queue.OpaService.wmEnviarDescargoFechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wmEnviarDescargoFechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Index.Queue.OpaService.clsRespuestaDescargo wmEnviarDescargoFechaResult;
        
        public wmEnviarDescargoFechaResponseBody() {
        }
        
        public wmEnviarDescargoFechaResponseBody(Index.Queue.OpaService.clsRespuestaDescargo wmEnviarDescargoFechaResult) {
            this.wmEnviarDescargoFechaResult = wmEnviarDescargoFechaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOPASoapChannel : Index.Queue.OpaService.WSOPASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOPASoapClient : System.ServiceModel.ClientBase<Index.Queue.OpaService.WSOPASoap>, Index.Queue.OpaService.WSOPASoap {
        
        public WSOPASoapClient() {
        }
        
        public WSOPASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOPASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOPASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOPASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Index.Queue.OpaService.TestResponse Index.Queue.OpaService.WSOPASoap.Test(Index.Queue.OpaService.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public Index.Queue.OpaService.clsRespuestaDescargo Test() {
            Index.Queue.OpaService.TestRequest inValue = new Index.Queue.OpaService.TestRequest();
            inValue.Body = new Index.Queue.OpaService.TestRequestBody();
            Index.Queue.OpaService.TestResponse retVal = ((Index.Queue.OpaService.WSOPASoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Index.Queue.OpaService.TestResponse> Index.Queue.OpaService.WSOPASoap.TestAsync(Index.Queue.OpaService.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Index.Queue.OpaService.TestResponse> TestAsync() {
            Index.Queue.OpaService.TestRequest inValue = new Index.Queue.OpaService.TestRequest();
            inValue.Body = new Index.Queue.OpaService.TestRequestBody();
            return ((Index.Queue.OpaService.WSOPASoap)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Index.Queue.OpaService.wmValidarDescargoResponse Index.Queue.OpaService.WSOPASoap.wmValidarDescargo(Index.Queue.OpaService.wmValidarDescargoRequest request) {
            return base.Channel.wmValidarDescargo(request);
        }
        
        public Index.Queue.OpaService.clsRespuestaDescargo wmValidarDescargo(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport) {
            Index.Queue.OpaService.wmValidarDescargoRequest inValue = new Index.Queue.OpaService.wmValidarDescargoRequest();
            inValue.Body = new Index.Queue.OpaService.wmValidarDescargoRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psExportadorNit = psExportadorNit;
            inValue.Body.psPolizaImportacion = psPolizaImportacion;
            inValue.Body.pLineaPolizaImport = pLineaPolizaImport;
            inValue.Body.pdUnidades = pdUnidades;
            inValue.Body.psPolizaExportacion = psPolizaExportacion;
            inValue.Body.piLineaPolizaExport = piLineaPolizaExport;
            Index.Queue.OpaService.wmValidarDescargoResponse retVal = ((Index.Queue.OpaService.WSOPASoap)(this)).wmValidarDescargo(inValue);
            return retVal.Body.wmValidarDescargoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmValidarDescargoResponse> Index.Queue.OpaService.WSOPASoap.wmValidarDescargoAsync(Index.Queue.OpaService.wmValidarDescargoRequest request) {
            return base.Channel.wmValidarDescargoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Index.Queue.OpaService.wmValidarDescargoResponse> wmValidarDescargoAsync(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport) {
            Index.Queue.OpaService.wmValidarDescargoRequest inValue = new Index.Queue.OpaService.wmValidarDescargoRequest();
            inValue.Body = new Index.Queue.OpaService.wmValidarDescargoRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psExportadorNit = psExportadorNit;
            inValue.Body.psPolizaImportacion = psPolizaImportacion;
            inValue.Body.pLineaPolizaImport = pLineaPolizaImport;
            inValue.Body.pdUnidades = pdUnidades;
            inValue.Body.psPolizaExportacion = psPolizaExportacion;
            inValue.Body.piLineaPolizaExport = piLineaPolizaExport;
            return ((Index.Queue.OpaService.WSOPASoap)(this)).wmValidarDescargoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Index.Queue.OpaService.wmExistePolizaResponse Index.Queue.OpaService.WSOPASoap.wmExistePoliza(Index.Queue.OpaService.wmExistePolizaRequest request) {
            return base.Channel.wmExistePoliza(request);
        }
        
        public bool wmExistePoliza(string psUsuario, string psClave, string psPoliza, string psTipoPoliza) {
            Index.Queue.OpaService.wmExistePolizaRequest inValue = new Index.Queue.OpaService.wmExistePolizaRequest();
            inValue.Body = new Index.Queue.OpaService.wmExistePolizaRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psPoliza = psPoliza;
            inValue.Body.psTipoPoliza = psTipoPoliza;
            Index.Queue.OpaService.wmExistePolizaResponse retVal = ((Index.Queue.OpaService.WSOPASoap)(this)).wmExistePoliza(inValue);
            return retVal.Body.wmExistePolizaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmExistePolizaResponse> Index.Queue.OpaService.WSOPASoap.wmExistePolizaAsync(Index.Queue.OpaService.wmExistePolizaRequest request) {
            return base.Channel.wmExistePolizaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Index.Queue.OpaService.wmExistePolizaResponse> wmExistePolizaAsync(string psUsuario, string psClave, string psPoliza, string psTipoPoliza) {
            Index.Queue.OpaService.wmExistePolizaRequest inValue = new Index.Queue.OpaService.wmExistePolizaRequest();
            inValue.Body = new Index.Queue.OpaService.wmExistePolizaRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psPoliza = psPoliza;
            inValue.Body.psTipoPoliza = psTipoPoliza;
            return ((Index.Queue.OpaService.WSOPASoap)(this)).wmExistePolizaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Index.Queue.OpaService.wmEnviarDescargoResponse Index.Queue.OpaService.WSOPASoap.wmEnviarDescargo(Index.Queue.OpaService.wmEnviarDescargoRequest request) {
            return base.Channel.wmEnviarDescargo(request);
        }
        
        public Index.Queue.OpaService.clsRespuestaDescargo wmEnviarDescargo(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport) {
            Index.Queue.OpaService.wmEnviarDescargoRequest inValue = new Index.Queue.OpaService.wmEnviarDescargoRequest();
            inValue.Body = new Index.Queue.OpaService.wmEnviarDescargoRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psExportadorNit = psExportadorNit;
            inValue.Body.psPolizaImportacion = psPolizaImportacion;
            inValue.Body.pLineaPolizaImport = pLineaPolizaImport;
            inValue.Body.pdUnidades = pdUnidades;
            inValue.Body.psPolizaExportacion = psPolizaExportacion;
            inValue.Body.piLineaPolizaExport = piLineaPolizaExport;
            Index.Queue.OpaService.wmEnviarDescargoResponse retVal = ((Index.Queue.OpaService.WSOPASoap)(this)).wmEnviarDescargo(inValue);
            return retVal.Body.wmEnviarDescargoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmEnviarDescargoResponse> Index.Queue.OpaService.WSOPASoap.wmEnviarDescargoAsync(Index.Queue.OpaService.wmEnviarDescargoRequest request) {
            return base.Channel.wmEnviarDescargoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Index.Queue.OpaService.wmEnviarDescargoResponse> wmEnviarDescargoAsync(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport) {
            Index.Queue.OpaService.wmEnviarDescargoRequest inValue = new Index.Queue.OpaService.wmEnviarDescargoRequest();
            inValue.Body = new Index.Queue.OpaService.wmEnviarDescargoRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psExportadorNit = psExportadorNit;
            inValue.Body.psPolizaImportacion = psPolizaImportacion;
            inValue.Body.pLineaPolizaImport = pLineaPolizaImport;
            inValue.Body.pdUnidades = pdUnidades;
            inValue.Body.psPolizaExportacion = psPolizaExportacion;
            inValue.Body.piLineaPolizaExport = piLineaPolizaExport;
            return ((Index.Queue.OpaService.WSOPASoap)(this)).wmEnviarDescargoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Index.Queue.OpaService.wmEnviarDescargoFechaResponse Index.Queue.OpaService.WSOPASoap.wmEnviarDescargoFecha(Index.Queue.OpaService.wmEnviarDescargoFechaRequest request) {
            return base.Channel.wmEnviarDescargoFecha(request);
        }
        
        public Index.Queue.OpaService.clsRespuestaDescargo wmEnviarDescargoFecha(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport, string psFechaCc) {
            Index.Queue.OpaService.wmEnviarDescargoFechaRequest inValue = new Index.Queue.OpaService.wmEnviarDescargoFechaRequest();
            inValue.Body = new Index.Queue.OpaService.wmEnviarDescargoFechaRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psExportadorNit = psExportadorNit;
            inValue.Body.psPolizaImportacion = psPolizaImportacion;
            inValue.Body.pLineaPolizaImport = pLineaPolizaImport;
            inValue.Body.pdUnidades = pdUnidades;
            inValue.Body.psPolizaExportacion = psPolizaExportacion;
            inValue.Body.piLineaPolizaExport = piLineaPolizaExport;
            inValue.Body.psFechaCc = psFechaCc;
            Index.Queue.OpaService.wmEnviarDescargoFechaResponse retVal = ((Index.Queue.OpaService.WSOPASoap)(this)).wmEnviarDescargoFecha(inValue);
            return retVal.Body.wmEnviarDescargoFechaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Index.Queue.OpaService.wmEnviarDescargoFechaResponse> Index.Queue.OpaService.WSOPASoap.wmEnviarDescargoFechaAsync(Index.Queue.OpaService.wmEnviarDescargoFechaRequest request) {
            return base.Channel.wmEnviarDescargoFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Index.Queue.OpaService.wmEnviarDescargoFechaResponse> wmEnviarDescargoFechaAsync(string psUsuario, string psClave, string psExportadorNit, string psPolizaImportacion, int pLineaPolizaImport, double pdUnidades, string psPolizaExportacion, int piLineaPolizaExport, string psFechaCc) {
            Index.Queue.OpaService.wmEnviarDescargoFechaRequest inValue = new Index.Queue.OpaService.wmEnviarDescargoFechaRequest();
            inValue.Body = new Index.Queue.OpaService.wmEnviarDescargoFechaRequestBody();
            inValue.Body.psUsuario = psUsuario;
            inValue.Body.psClave = psClave;
            inValue.Body.psExportadorNit = psExportadorNit;
            inValue.Body.psPolizaImportacion = psPolizaImportacion;
            inValue.Body.pLineaPolizaImport = pLineaPolizaImport;
            inValue.Body.pdUnidades = pdUnidades;
            inValue.Body.psPolizaExportacion = psPolizaExportacion;
            inValue.Body.piLineaPolizaExport = piLineaPolizaExport;
            inValue.Body.psFechaCc = psFechaCc;
            return ((Index.Queue.OpaService.WSOPASoap)(this)).wmEnviarDescargoFechaAsync(inValue);
        }
    }
}
